version: "3"
services:
  room-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=room_db
    image: mysql:8.0.0
    ports:
      - 0.0.0.0:7200:3306
  phpmyadmin:
    depends_on:
      - room-service-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container_for_nodejs
    environment:
      PMA_HOST: room-service-db
    links:
      - room-service-db:room-service-db
    ports:
      - 8080:80
    restart: always
  nodeapp-docker:
    build: "./server"
    depends_on:
      - room-service-db
    environment:
      - API_PORT=8000
      - DB_URI=mysql://root:password@room-service-db/room_db?charset=UTF8
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - room-service-db
    command: npm start
